SprinklerBundle\Entity\Zone:
    type: entity
    table: zone
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        relay:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
        name:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
        image:
            type: boolean
            nullable: false
        override:
            type: boolean
            nullable: false
            options:
                default: '0'
        overrideendtime:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            column: overrideEndTime
    oneToMany:
        timers:
            targetEntity: Timer
            mappedBy: zone
    lifecycleCallbacks: {  }
