services:
#    sprinkler.example:
#        class: SprinklerBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    overcast:
        class: VertigoLabs\Overcast\Overcast
        arguments: ["%forecast_api%"]
parameters:
    forecast_api: 52a922ed7f8951840188f2b09dd90dd4